services:
  budgetfe-dev:
    build:
      context: .
      target: dev
    container_name: budgetfe-dev
    ports:
      - "4200:4200"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev

  budgetfe:
    build:
      context: .
      target: runner
    container_name: budgetfe
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
    profiles:
      - prod
